# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('status', models.IntegerField(max_length=5)),
                ('auth', models.IntegerField(max_length=5)),
                ('loginTime', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
            ],
        ),
    ]
